name: "Notify Release Approver"
on:
  schedule:
    - cron: '0 20 * * 2' # Run every tuesday at 20:00 UTC (12 noon Pacific)
  workflow_dispatch:


jobs:
  notify_approver:
    runs-on: ubuntu-20.04
    env:
      PAGERDUTY_TOKEN: ${{ secrets.pagerduty_token }}
      SLACK_TOKEN: ${{ secrets.slack_token }}
      CCI_TOKEN: ${{ secrets.cci_token }}
    steps:
      - uses: actions/checkout@v2.2.0
      - name: Add APIs to PATH
        run: echo ".github/scripts/apis/" >> $GITHUB_PATH
      - name: Get On-Call Engineer
        id: fetch_eng
        run: |
          ENGINEER_ID=$(pagerduty '??whos_oncall' | jq -rc '.id')
          ENGINEER_EMAIL=$(pagerduty "?users/$ENGINEER_ID" | jq -rc '.user.email')
          echo "oncall_email=$ENGINEER_EMAIL" >> $GITHUB_OUTPUT
      - name: Get Slack ID
        id: fetch_slack
        run: |
          OCEMAIL="${{ steps.fetch_eng.outputs.oncall_email }}"
          OCID=$(slack '?users.lookupByEmail' "{\"email\": \"$OCEMAIL\"}" | jq -rc '.user.id')
          echo "oncall_id=$OCID" >> $GITHUB_OUTPUT
      - name: Find CircleCI Workflow
        id: fetch_cci
        run: |
          LATEST_PROD=$(circleci '??prod_latest')
          PIPELINE=$(echo "$LATEST_PROD" | jq -rc '.pipeline')
          WORKFLOW=$(echo "$LATEST_PROD" | jq -rc '.workflow')
          echo "cci_url=https://app.circleci.com/pipelines/github/metropolis-io/site/$PIPELINE/workflows/$WORKFLOW" >> $GITHUB_OUTPUT
      - name: Send Slack Message
        run: |
          CONVO=$(slack '!conversations.open' "{\"users\": \"${{ steps.fetch_slack.outputs.oncall_id }}\"}" | jq -rc '.channel.id')
          
          CONF=$(jq -nc --arg channel "$CONVO" \
                       --arg template ".github/messages/approve_release.json" \
                       --arg target "${{ steps.fetch_cci.outputs.cci_url }}" \
                       '$ARGS.named')
          slack '!!send_template' "$CONF"
