name: Release
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  test:
    environment: release
    runs-on: ubuntu-latest
    container:
      image: "registry.digitalocean.com/anemoi/bazelbase:latest"
      credentials:
        username: ${{ secrets.digitalocean_token }}
        password: ${{ secrets.digitalocean_token }}
    steps:
      # - uses: actions/checkout@v2
      - name: Configure cwd
        run: sudo chown bazelbase:staff .
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo ${{ env.RELEASE_VERSION }}
          BP=$(which bazel)
          echo $BP
          echo $(whoami)
