name: Validate PR Title

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  validate_pr:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Lint PR Title
        id: dolint
        run: python .github/scripts/verify_pr.py "${{ github.event.pull_request.title }}" "${{ github.head_ref }}"
      - name: Update PR Title
        if: steps.dolint.outputs.new_title != ""
        uses: gr2m/create-or-update-pull-request-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: ${{ steps.dolint.outputs.new_title }}
