name: Validate PR Title

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  validate_pr:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Lint PR Title
        id: dolint
        run: python .github/scripts/lint_pr.py "${{ github.event.pull_request.title }}" "${{ github.head_ref }}"
      - name: Update PR Title
        if: steps.dolint.outputs.new_title != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install requests
          python .github/scripts/update_pr.py "${{steps.dolint.outputs.new_title}}" "${{ github.event.pull_request.base.repo.full_name }}" "${{ github.event.pull_request.number }}"
            
