name: Validate PR Title

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  validate_pr:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Lint PR Title
        id: dolint
        run: python .github/scripts/verify_pr.py "${{ github.event.pull_request.title }}" "${{ github.head_ref }}"
      - name: Update PR Title
        if: steps.dolint.outputs.new_title != ''
        run: |
          curl \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \ 
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.event.pull_request.base.repo.full_name }}/pulls/${{ github.event.pull_request.number }} \
            -d '{"title":"${{ steps.dolint.outputs.new_title }}"}'
